---
title: "charts notes"
author: "Elizabeth Permina"
date: "2/12/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
if(!require("plotrix"))
{install.packages("plotrix")}
if(!require("DiagrammeR")){
  install.packages("DiagrammeR")
}
if(!require("plan")){
  install.packages("plan")
}
library(plan)
library(DiagrammeR)
library(plotrix)
library(tidyverse)
```

## DiagrammeR

## mermaid Gantt example

```{r}
mermaid("gantt
        Section Initiation
        Planning  :a1, 2022-02-12, 10d
        Data processing :after a1, 30d")
```

## graphViz 

basic structure

```{r, eval=FALSE}
[strict] (graph | digraph) [ID] '{' stmt_list '}'
```

graphViz example

```{r}
grViz("
digraph boxes_and_circles {

  # a 'graph' statement
  graph [overlap = true, fontsize = 10]

  # several 'node' statements
  node [shape = box,
        fontname = Helvetica]
  A; B; C; D; E; F

  node [shape = circle,
        fixedsize = true,
        width = 0.9] // sets as circles
  1; 2; 3; 4; 5; 6; 7; 8

  # several 'edge' statements
  A->1 B->2 B->3 B->4 C->A
  1->D E->A 2->4 1->5 1->F
  E->6 4->6 5->7 6->7 3->8
}
")
```

### node data frames

graphs start with a node data frame

```{r}
ndf<-create_node_df(n=3, label = T)
ndf
```

```{r}
ndf<-create_node_df(n=3, type= c("A", "A", "B"),   label = T)
ndf
```

```{r}

```

Edge dataframe

```{r}
edf<-create_edge_df(from = c(1,2), to = c(2,3), rel = c("X", "Y"))

```

Create and render graph

```{r}
the_graph <- create_graph(nodes_df = ndf, edges_df = edf)
the_graph %>% render_graph(output = "VisNetwork")
```

### operations
```{r}
the_graph %>% count_nodes()
the_graph %>% count_edges()
the_graph %>% get_node_ids(conditions = type == "X")
the_graph %>% get_edges(conditions = type == "X")
the_graph

```


### styles in diagrammeR

```{r, eval=FALSE}
abc [fillcolor = red]
color
fontcolor
shape
style
sides
alpha
peripheries
```


